name: Release Build (32-bit)

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write  

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW32
        update: true
        install: >-
          mingw-w64-i686-gcc
          mingw-w64-i686-binutils
          mingw-w64-i686-tools-git
    
    - name: Build
      shell: msys2 {0}
      run: |
        if [ ! -d "bin" ]; then mkdir bin; fi
        echo "1 24 src/app.manifest" > src/app.rc
        echo "400 ICON img/todo.ico" >> src/app.rc
        windres src/app.rc -O coff -o src/app.res
        gcc src/main.c src/todo.c src/gui.c src/utils/search.c src/app.res -o bin/todo32.exe -m32 -mwindows -lcomctl32 -luxtheme -Os -s -static

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: bin/todo32.exe
        name: Release ${{ github.ref_name }} (32-bit)
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 